name: Build Development

on:
  push:
    branches: [master]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin

      - name: Build
        uses: gradle/gradle-build-action@v3
        with:
          arguments: clean build

      - name: Extract repository name
        run: echo "NAME=$(basename ${{ github.repository }})" >> $GITHUB_ENV

      - name: Upload Build
        uses: marvinpinto/action-automatic-releases@master
        with:
          title: "${{ env.NAME }}"
          automatic_release_tag: "latest"
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          files: "target/*.jar"
          prerelease: false
